/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;

import Funcionalidade.Facade;
import Funcionalidade.Modelo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henriquefaria
 */
public class ModelosFrame extends javax.swing.JFrame {

    private final Facade facade;

    /**
     * Creates new form ModelosFrame
     */
    public ModelosFrame(Facade facade) throws SQLException {
        this.facade = facade;
        initComponents();
        

        
        String[] colunas = { "Nome","Imagem","Preço","Ação" };
        Object[][] data = null;

        List <Modelo> modelos = new ArrayList<>();
        try {
            modelos = new ArrayList<Modelo>(facade.getModelos());
        } catch (SQLException ex) {
            Logger.getLogger(ModelosFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NullPointerException e){
            System.out.println("Erro no acesso á base de dados");
        }

        System.out.println(modelos.size());
        data = new Object[modelos.size()][4];
        for (int r=0; r<modelos.size(); r++) {
            data[r][0] = modelos.get(r).getNome();
            data[r][1] = new ImageIcon(getClass().getResource(modelos.get(r).getImg()));
            data[r][2] = modelos.get(r).getPreco();
            data[r][3] = "Selecionar";
        }
    DefaultTableModel model = new DefaultTableModel(data, colunas){
        @Override
      public Class getColumnClass(int column) {
        return (column == 1) ? Icon.class : Object.class;
      }
     public boolean isCellEditable(int row, int column) {
            if( column == 3)return true; return false;
        }};
        jTable1.setModel(model);
        jTable1.getColumn("Ação").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Ação").setCellEditor(
        new ButtonModelos(new JCheckBox(),this,jTable1,modelos,facade));
      jTable1.setRowHeight(120);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Modelos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
