/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;
import Funcionalidade.Componente;
import Funcionalidade.Facade;
import Funcionalidade.Pacote;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Filipe Universidade
 */
public class PacotesFrame2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form SelecaoTable2
     */
    public PacotesFrame2(Facade facade,Selecao selecao) throws SQLException {
    initComponents();
    this.facade = facade;
    
         BasicInternalFrameUI ui = (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        JComponent title = ui.getNorthPane();

// to remove
ui.setNorthPane(null);

        String[] colunas = { "Nome","Imagem", "Selecionar" };
        Object[][] data = null;

        list = facade.getPacoteDAO().getAllPacotes();
        if(list.size()>0){
        data = new Object[list.size()][3];
        for (int r=0; r<list.size(); r++) {
            data[r][0] = new ImageIcon(getClass().getResource(list.get(r).getImage()));
            data[r][1] = list.get(r).getNome();
            data[r][2] = "Selecionar";
        }
        }
    
            
         /*   { { aboutIcon, , "4343 €","Remover" }, { aboutIcon, "Jantes V93 ' 19", "323 €","Remover" },
        { aboutIcon, "Pneus", "432 €","Remover" }, { aboutIcon, "Pintura", "343 €","Remover" } };*/
    DefaultTableModel model = new DefaultTableModel(data, colunas){
        @Override
      public Class getColumnClass(int column) {
        return (column == 0) ? Icon.class : Object.class;
      }
     public boolean isCellEditable(int row, int column) {
            if( column == 2)return true; return false;
        }};
      jTable1.setModel(model);
      jTable1.getColumn("Selecionar").setCellRenderer(new ButtonRenderer());
      jTable1.getColumn("Selecionar").setCellEditor(
      new ButtonSelecionarPacote(new JCheckBox(),facade,jTable1,list,selecao));
     // jTable1.getColumnModel().getColumn(0).setMinHeight(400); 
      jTable1.setRowHeight(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private Facade facade;
    private List<Pacote> list;
}
