
import java.awt.BorderLayout;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henriquefaria
 */
public class SelecaoModeloFinal extends javax.swing.JFrame {

    /**
     * Creates new form SelecaoModeloFinal
     */
    public SelecaoModeloFinal() {
        initComponents();
        ratio1 = jPanel2.getWidth()/jScrollPane1.getWidth();
        ratio2 = jPanel2.getHeight()/jScrollPane1.getHeight();
        jScrollPane1.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                resizePreviewJPanel(jPanel2, jScrollPane1);
            }
        });
        ratio3 = jScrollPane1.getWidth()/this.getWidth();
        ratio4 = jScrollPane1.getHeight()/this.getHeight();
        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                resizePreviewJScroll(jScrollPane1, this);
            }
        });
        jPanel2.setLayout(new java.awt.GridLayout(2,jPanel2.getWidth()/200,50,20));
        jScrollPane1.setViewportView(jPanel2);
        int nImagens = 10;
        // correr várias opções de imagens
        for(int i = 0; i< nImagens; i++){   
            JLabel img;
            JLabel nome;
            JPanel modelo = new JPanel();
            modelo.setLayout(new BorderLayout());
            modelo.setSize(200,200);
            img = new JLabel(new ImageIcon(getClass().getResource("/resources/imagem0.jpg"),"MyImage"));
            nome = (new JLabel("Modelo" + i));
            nome.setHorizontalAlignment(SwingConstants.CENTER);
            img.setSize(150,100);//setBounds(10, 10, 150, 100);
            nome.setSize(50,20);//setBounds(60, 120, 50, 20);
            modelo.add(img, BorderLayout.CENTER);
            modelo.add(nome,BorderLayout.SOUTH);
            jPanel2.add(modelo);
        }
    }
    
    private void resizePreviewJPanel(JPanel innerPanel, JPanel container) {
        innerPanel.setSize((int)ratio1*container.getWidth(), (int)ratio2*container.getHeight());
        container.revalidate();
    }
    private void resizePreviewJScroll(JPanel innerPanel, JPanel container) {
        innerPanel.setSize((int)ratio3*container.getWidth(), (int)ratio4*container.getHeight());
        container.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modelos");

        jPanel2.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoModeloFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoModeloFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoModeloFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoModeloFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoModeloFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private float ratio1;
    private float ratio2;
    private float ratio3;
    private float ratio4;
}
